import React from 'react';
import { BookOpen, Building2, FileText, ShieldCheck, UserRound } from 'lucide-react';
interface AboutViewProps { darkMode: boolean; }
export const AboutView: React.FC<AboutViewProps> = ({ darkMode }) => {
  const card = `rounded-2xl border p-5 ${darkMode ? 'bg-slate-800 border-slate-700 text-slate-100' : 'bg-white border-slate-200 text-slate-800'}`;
  return <div className="space-y-6 max-w-4xl">
    <div><h2 className="text-xl font-bold">Acerca de CPU Batán</h2><p className={darkMode ? 'text-slate-400 text-sm mt-1' : 'text-slate-500 text-sm mt-1'}>Información institucional, condiciones de uso y créditos.</p></div>
    <div className={card}><div className="flex items-center gap-3 mb-3"><Building2 className="w-5 h-5 text-blue-500"/><h3 className="font-bold">Desarrollado para La Clave Argentina</h3></div><p className="text-sm leading-6">CPU Batán — Control de Asistencia es una herramienta de gestión desarrollada para <strong>La Clave Argentina</strong>.</p><p className="text-xs mt-3 opacity-70">Crédito de desarrollo: La Clave Argentina.</p></div>
    <div className={card}><div className="flex items-center gap-3 mb-3"><FileText className="w-5 h-5 text-blue-500"/><h3 className="font-bold">Condiciones de uso</h3></div><ul className="space-y-2 text-sm leading-6 list-disc pl-5"><li>El sistema debe utilizarse únicamente para fines institucionales y por personas autorizadas.</li><li>La cuenta administradora es responsable de los datos cargados, sus correcciones y los permisos otorgados.</li><li>No se deben cargar datos personales de terceros sin autorización y fundamento legítimo.</li><li>Los respaldos deben realizarse periódicamente y verificarse antes de eliminar o modificar información.</li></ul></div>
    <div className={card}><div className="flex items-center gap-3 mb-3"><ShieldCheck className="w-5 h-5 text-emerald-500"/><h3 className="font-bold">Alcance y limitación de responsabilidad</h3></div><p className="text-sm leading-6">La herramienta se entrega como apoyo administrativo. La Clave Argentina y el desarrollador no garantizan disponibilidad permanente, ausencia de errores, conservación indefinida de la información ni resultados derivados de decisiones tomadas con los datos del sistema.</p><p className="text-sm leading-6 mt-3">La responsabilidad de revisar asistencias, vencimientos, estados, respaldos y decisiones institucionales corresponde exclusivamente a la administración y a las personas autorizadas. La información del sistema no reemplaza asesoramiento legal, laboral, médico ni profesional.</p></div>
    <div className={card}><div className="flex items-center gap-3 mb-3"><UserRound className="w-5 h-5 text-amber-500"/><h3 className="font-bold">Privacidad y seguridad</h3></div><p className="text-sm leading-6">El acceso debe mantenerse protegido. No compartas contraseñas ni permitas el uso de la sesión administradora por personas no autorizadas. Ante un incidente, error o pérdida de información, suspendé el uso y verificá el último respaldo disponible.</p></div>
    <div className={card}><div className="flex items-center gap-3 mb-3"><BookOpen className="w-5 h-5 text-blue-500"/><h3 className="font-bold">Aceptación</h3></div><p className="text-sm leading-6">El uso de la aplicación implica la aceptación de estas condiciones. Estas condiciones pueden actualizarse cuando cambien las funciones o necesidades institucionales.</p></div>
    <p className="text-xs text-slate-500">Última actualización: 08/09/2026. Este texto es informativo y no constituye asesoramiento jurídico.</p>
  </div>;
};
